### PR TITLE
Add documentation of Travis-CI usage in README.

### PR DESCRIPTION
**Pull request by brenns10**

### CODE REVIEW

**Comment by timtadh** [comment]
Looks good I would also do add a requirements file and explain the local setup. aka

```
$ pip freeze >> requirements.txt
```

Then something about

```
$ virtualenv --no-site-packages env
$ source env/bin/activate
$ pip install -r requirements.txt
$ make html
$ echo 'off to races'
```

**Comment by brenns10** [comment]
I'll do that, but I think I may avoid the requirements file, mostly because it'll get us stuck on a sphinx version, and Travis currently doesn't use it.

**Comment by timtadh** [comment]
@brenns10 just don't include the versions in the requirements file. Just put `sphinx` in there.

**Comment by brenns10** [comment]
Should be good to go now.

**Comment by brenns10** [comment]
Heh, in testing my documentation, I noticed Sphinx gave some wonky messages because it stole documentation files from the `virtualenv`, so I added `venv` and `env` as directories that Sphinx will ignore when searching for docs.

**Comment by timtadh** [comment]
good idea :+1:

**Pull request merged**
