### PR TITLE
Add Slack document for linking to in an announcement email.

### PR DESCRIPTION
**Pull request by brenns10**
What do you think?  Particularly important issues would be rules and the transfer of ownership/administration.

### CODE REVIEW

**Comment by ajm188** [comment]
lg2m. might want to give @thomasrussellmurphy a chance to look it over

**Comment by mtbentley** [comment]
Looks good to me.  Should probably have one more set of eyes read before merging due to its length

**Comment by brenns10** [comment]
Totally fine on more eyes.  I mean, we probably don't want to send out an email till tomorrow anyway.

**Comment by StephHippo** [comment]
Looks good to me. Especially like the emphasis on being kind and hoping we never have to enforce that. Makes it clear that we will.

**Comment by brenns10** [comment]
Cool.  I'll wait for @thomasrussellmurphy's :+1: before merge?

**Comment by thomasrussellmurphy** [comment]
Read through. Nothing seems particularly out of place or unreasonable.

**Comment by brenns10** [comment]
:ship:ing

**Pull request merged**
