### PR TITLE
Add rule to discourage @channel-ing in a large channel

### PR DESCRIPTION
**Pull request by mtbentley**

### CODE REVIEW

**Comment by StephHippo** [comment]
Why are we doing this?

**Comment by mtbentley** [comment]
To discourage people from using @channel in #general.  The wording might need some changes, but you don't want to notify everyone in slack unless needed.  Especially if we try to advertise the existence of the slack more (which some people seem to be a fan of)

**Comment by StephHippo** [comment]
There are times when this is useful- especially when organizing events and there's something that needs taken care of IMMEDIATELY. 

The current wording is a bit of a conflict:
"Avoid notifying everyone in large channels without a very good reason.  This means don't use @channel in a large channel or @everyone anywhere."

First sentence says only with a good reason.
Second sentence implies never. 

Do not discourage people from alerting for this situation

**Comment by ajm188** [comment]
I agree with @StephHippo . We need @channel and @everyone . Slack issues a warning. If it becomes a problem, we'll just give a friendly reminder to the offender.

**Comment by brenns10** [comment]
I was about to say the same thing.  Phones all have schedulable quiet hours, so there's no risk of waking people.  So long as @ channel isn't liberally applied, it is fine.  Let's not jump the gun on a problem that may not happen.

**Comment by mtbentley** [comment]
This doesn't seem to be very popular. Closing for now.

**Pull request closed without merging**
