### PR TITLE
Add CAS article based on old wiki contents.

### PR DESCRIPTION
**Pull request by brenns10**
I'm not sure I'm totally satisfied with the contents of this article yet.  Still feels bloated and dated.  But I wanted to get this up, because CAS is one of the most severely under-documented items at Case right now.

We need to merge the directory reorganization PR before we merge this.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Do we have links to the current open-sourced implementations that people have done?

**Comment by brenns10** [comment]
RubyCAS is the one I'm aware of, as well as django-cas. I added these to
the article, near the end.

**Comment by timtadh** [comment]
:+1: consider doing a rebase on master and fixing up conflicts prior to merge (or merging in master into this and fixing the conflicts, then doing the merge the other way).

**Comment by brenns10** [comment]
Rebase and `git push -f` does the trick!

**Pull request merged**
