### PR TITLE
Alumnify @mason.

### PR DESCRIPTION
**Pull request by brenns10**
:'(

### CODE REVIEW

**Comment by brenns10** [comment]
lol @ajm188, sorry whoever mason is on GitHub :P

**Comment by StephHippo** [comment]
Sad but also funny.

**Comment by ajm188** [comment]
Haha; I've thought about reaching out to this mystery person to acquire their handle &mdash; they seem fairly inactive.

But, changes lgtm 👍

**Comment by ajm188** [comment]
You might want to amend the commit message to mention my github handle, though.

**Comment by brenns10** [comment]
Closing and resubmitting as opposed to editing public git history.

Will just merge the PR since we have shipits here.

**Pull request closed without merging**
